# Generated by Django 5.1.6 on 2025-03-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brandmodel_productmodel_img_productmodel_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='BrandModel',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
