# Generated by Django 5.1.6 on 2025-03-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_bannermodel_colormodel_sizemodel_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colormodel',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
