# Generated by Django 5.1.6 on 2025-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_colormodel_name_alter_sizemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
